# Generated by Django 5.2.8 on 2025-11-13 11:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpage_configuratorpage_contactpage_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLinksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar_links', wagtail.fields.StreamField([('page_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {})}, null=True, verbose_name='Navbar Links')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
