# Generated by Django 5.2.8 on 2025-11-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_navbarlinkspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarlinkspage',
            options={'verbose_name': 'Navbar Links', 'verbose_name_plural': 'Navbar Links'},
        ),
    ]
