# Generated by Django 5.2.8 on 2025-11-17 10:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallerypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlinkspage',
            name='navbar_links',
            field=wagtail.fields.StreamField([('page_link', 2), ('multiple_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('page_link', 2)]], {})}, null=True, verbose_name='Navbar Links'),
        ),
    ]
