# Generated by Django 5.2.8 on 2025-11-18 13:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_footerlinkspage_socialmediasettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinkspage',
            name='first_column',
            field=wagtail.fields.StreamField([('bold_page_link', 2), ('regular_page_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {})}, null=True, verbose_name='Links in First Column'),
        ),
        migrations.AlterField(
            model_name='footerlinkspage',
            name='second_column',
            field=wagtail.fields.StreamField([('bold_page_link', 2), ('regular_page_link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {})}, null=True, verbose_name='Links in Second Column'),
        ),
    ]
