# Generated by Django 5.2.8 on 2026-03-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpagecoldsystems',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='collectionpagehotsystems',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
