# Generated by Django 5.2.8 on 2025-11-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rootredirectpage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='MainPage',
        ),
    ]
