# Generated by Django 5.2.8 on 2025-11-18 13:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_navbarlinkspage_navbar_links'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_column', wagtail.fields.StreamField([('page_link', 2), ('multiple_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('page_link', 2)]], {})}, null=True, verbose_name='Links in First Column')),
                ('second_column', wagtail.fields.StreamField([('page_link', 2), ('multiple_link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Tekst Linku', 'max_length': 255, 'null': True, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'blank': True, 'label': 'Strona do przekierowania', 'null': True, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1)]], {}), 3: ('wagtail.blocks.StreamBlock', [[('page_link', 2)]], {})}, null=True, verbose_name='Links in Second Column')),
            ],
            options={
                'verbose_name': 'Footer Links',
                'verbose_name_plural': 'Footer Links',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_x', models.URLField(blank=True, null=True, verbose_name='URL X')),
                ('url_facebook', models.URLField(blank=True, null=True, verbose_name='URL Facebook')),
                ('url_linkedin', models.URLField(blank=True, null=True, verbose_name='URL LinkedIn')),
                ('url_instagram', models.URLField(blank=True, null=True, verbose_name='URL Instagram')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media - Linki',
                'verbose_name_plural': 'Social Media - Linki',
            },
        ),
    ]
